apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: osp9b5z4m-go
  janus-idp.io/tekton: osp9b5z4m-go
  backstage.io/kubernetes-id: osp9b5z4m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: osp9b5z4m-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
